//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "bassinet_nft")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub package_id: String,
    #[sea_orm(unique)]
    pub collection_id: String,
    pub description: Option<String>,
    pub collection_url: Option<String>,
    pub limit: Option<i64>,
    pub minting_price: i64,
    pub rewards_quantity: Option<i64>,
    pub mint_id: Option<String>,
    pub policy_id: Option<String>,
    pub policy_cap_id: Option<String>,
    pub coin_id: Option<String>,
    pub coin_package_id: Option<String>,
    pub coin_treasury_lock_id: Option<String>,
    pub coin_admin_cap_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
