//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "chunk_list")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub file_hash: String,
    pub chunk_number: i32,
    pub chunk_size: i32,
    pub file_name: String,
    pub total_chunks: i32,
    pub created_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
