//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "collection_item")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub collection_id: String,
    pub seq: i32,
    pub title: Option<String>,
    pub description: Option<String>,
    pub created_time: DateTime,
    pub is_public: i32,
    pub author: String,
    pub category: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub content: Option<String>,
    pub path: Option<String>,
    pub hash: Option<String>,
    pub ipfs: Option<String>,
    pub status: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
